apiVersion: apps/v1
kind: Deployment
metadata:
  name: small-app-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: small-app-1
  template:
    metadata:
      labels:
        app: small-app-1
    spec:
      containers:
        - name: small-app-1-container
          image: gcr.io/my-project-id/small-app-1:container_2_$BUILD_ID
          ports:
            - containerPort: 8000



